# Generated by Django 3.0.8 on 2020-07-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SP', 'Soup & Stew'), ('SW', 'SWALLOW'), ('RM', 'Meal')], default='RM', max_length=20)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
    ]
