# Generated by Django 3.0.8 on 2020-07-22 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name_plural': 'Meals'},
        ),
        migrations.AddField(
            model_name='meals',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 7, 22, 22, 55, 2, 368240, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meals',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
