# Generated by Django 3.0.8 on 2020-08-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200722_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='meal_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
